import * as cheerio from 'cheerio';
import VendorSource from '../models/VendorSource.js';
import Vendor from '../models/Vendor.js';
import PriceChange from '../models/PriceChange.js';
import PriceHistory from '../models/PriceHistory.js';
function parsePrice(text){if(!text)return null;const m=text.replace(/\s/g,'').match(/(?:₹|Rs\.?|INR)?([0-9][0-9,]*(?:\.\d+)?)/i);return m?Number(m[1].replace(/,/g,'')):null;}
export async function checkSource(source){const started=new Date();try{const r=await fetch(source.url,{headers:{'user-agent':'PayrollIntelligenceBot/3.0 (+price verification)'},redirect:'follow'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const html=await r.text();const $=cheerio.load(html);let text='';if(source.extractionMethod==='css'&&source.cssSelector)text=$(source.cssSelector).first().text();else if(source.extractionMethod==='regex'&&source.pricePattern){const m=html.match(new RegExp(source.pricePattern,'i'));text=m?.[1]||m?.[0]||'';}else if(source.extractionMethod==='jsonld'){text=$('script[type="application/ld+json"]').text();}else text=$('body').text();const price=parsePrice(text);source.lastCheckedAt=started;source.lastError=undefined;if(price===null){source.lastError='Price not found';await source.save();return {ok:false,error:'Price not found'};}source.lastSuccessAt=new Date();await source.save();const vendor=await Vendor.findById(source.vendorId);const old=vendor?.plans?.[0]?.price??null;let type='NO_CHANGE',pct=null;if(old===null)type='NEW_PRICE';else if(price>old){type='PRICE_INCREASE';pct=((price-old)/old)*100;}else if(price<old){type='PRICE_DECREASE';pct=((price-old)/old)*100;}
if(type!=='NO_CHANGE'){await PriceChange.create({vendorId:vendor._id,sourceId:source._id,oldPrice:old,newPrice:price,priceText:text.slice(0,300),changeType:type,percentage:pct,status:'pending',confidence:source.confidence});}else await PriceHistory.create({vendorId:vendor._id,sourceId:source._id,price,priceText:text.slice(0,300),verified:true});return {ok:true,changed:type!=='NO_CHANGE',price,type};}catch(e){source.lastCheckedAt=started;source.lastError=e.message;await source.save();return {ok:false,error:e.message};}}
export async function runPriceUpdates(){const sources=await VendorSource.find({enabled:true}).limit(200);const results=[];for(const s of sources)results.push(await checkSource(s));return results;}
